/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js during setup.
// See https://nextjs.org/docs/basic-features/typescript for more information.
